### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by sandeshgb** [NextNC/nestjs-ses#1]
I installed your package, but the import statement gives error "Cannot find module '@nextm/nestjs-ses'.ts(2307)". Whereas I verified the node_modules directory, it is present.

Also one query, while importing you are using name as NestjsSesModule, but while  configuring it you are using SesModule why so?

Its also missing the index.js file while downloading it from npm.

**Comment by NextNC** [comment]
Thank you for opening an issue @sandeshgb!
Yes, you're right there is a typo in the Readme file. I will fix it right now.

**Comment by DonsWayo** [comment]
I have the same issue

Cannot find module '@nextm/nestjs-ses' or its corresponding type declarations.

3 import { SesModule } from '@nextm/nestjs-ses';

I see on the node modules, but vs code and when try to running is complain about it
