### ISSUE TITLE
Email content issue

### ISSUE THREAD

**Issue by sandeshgb** [NextNC/nestjs-ses#5]
In my email body, I've content which has brackets. ex: Welcome user(role).
If I remove brackets () it works fine else it gives me error "SignatureDoesNotMatch".
Also I tried same with square brackets [] it worked.

![nestjs-ses-err](https://user-images.githubusercontent.com/29796620/89106507-0e3f8880-d448-11ea-9599-13005eb5c715.png)

**Comment by sandeshgb** [comment]
@NextNC any progress over here...!!

**Comment by sandeshgb** [comment]
@NextNC Today I encountered one more content bug, I had a name with single quote in it and the same error occurred again.
Ex: Welcome to ABC's does not work.

**Comment by NextNC** [comment]
Hi @sandeshgb, 

Sorry for the late response.
Have you already tried to escape those characters?
I don't think this is related with this package since it's a simple wrapper of "node-ses"... You should check AWS SES documentation or open the issue in "node-ses" github if you don't find anything. 👍

**Comment by sandeshgb** [comment]
Yes, if I skip those characters the email works absolutely fine.
Firstly I found the round bracket scenario which took much of my time to
just identify this.
And today this single quote.

You can try out the scenarios mentioned above and provide feedback!!

**Comment by sandeshgb** [comment]
> Hi @sandeshgb,
> 
> Sorry for the late response.
> Have you already tried to escape those characters?
> I don't think this is related with this package since it's a simple wrapper of "node-ses"... You should check AWS SES documentation or open the issue in "node-ses" github if you don't find anything. +1

As you have suggested I referred node-ses for this and they had this issue, but they have mentioned its been fixed in their updated versions. You may need to check node-ses version.
Link for same: [node-ses issue](https://github.com/aheckmann/node-ses/issues/63#issue-610548625)

But even if you try to send email with body as follows it doesn't work.
Ex: Welcome Jeff(admin) or Welcome to ABC's

@NextNC 
Request you to take this on priority and revert.

**Comment by sandeshgb** [comment]
@NextNC  request you to update node-ses version to 3.0.2 in package.json

**Comment by NextNC** [comment]
Hi @sandeshgb just bumped
